### COMMON
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL57Dialect
        default_batch_fetch_size: 500
        hbm2ddl:
          auto: none

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: tst


---
spring.config.activate.on-profile: prod
