spring.config.activate.on-profile: local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    # DB초기화(schema.sql, data.sql) , [always : 기동 시 매번 동작, never : 기동 시 동작하지 않음]
    init:
      schema-locations: classpath*:initdata/h2db/schema.sql
      data-locations: classpath*:initdata/h2db/data.sql
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./target/h2db/db/application;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE
    # url: jdbc:h2:mem:woopidb;DATABASE_TO_UPPER=FALSE
    username: woopi
    password:

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod
